In [2]:
from pymoo.algorithms.soo.nonconvex.ga import GA
from pymoo.problems import get_problem
from pymoo.optimize import minimize
import numpy as np
from pymoo.termination import get_termination
from pymoo.core.callback import Callback

In [3]:
class MyCallback(Callback):
    def __init__(self) -> None:
        super().__init__()
        self.data["best"] = []

    def notify(self, algorithm):
        self.data["best"].append(algorithm.pop.get("F"))


In [4]:
problem = get_problem("ackley", n_var=2, a=20, b=1/5, c=2 * np.pi)

algorithm = GA(
    pop_size=100,
    eliminate_duplicates=True)

tc = get_termination("n_gen", 300)



res = minimize(problem,
               algorithm,
               tc,
               seed=1,
               callback=MyCallback(),
               verbose=True
               )

print("Best solution found: \nX = %s\nF = %s" % (res.X, res.F))


n_gen  |  n_eval  |     f_avg     |     f_min    
     1 |      100 |  2.063311E+01 |  1.302296E+01
     2 |      200 |  1.900891E+01 |  9.0345855011
     3 |      300 |  1.641033E+01 |  6.6295241603
     4 |      400 |  1.310275E+01 |  2.6542840416
     5 |      500 |  1.057375E+01 |  2.4358491215
     6 |      600 |  8.4410984590 |  2.0681757771
     7 |      700 |  6.5082797039 |  1.0585778446
     8 |      800 |  5.0488880687 |  1.0585778446
     9 |      900 |  3.8033499177 |  0.6981076515
    10 |     1000 |  3.0658015976 |  0.2875057909
    11 |     1100 |  2.6872443846 |  0.2875057909
    12 |     1200 |  2.3516848970 |  0.2875057909
    13 |     1300 |  1.9471624358 |  0.2758375066
    14 |     1400 |  1.6609617216 |  0.1421576674
    15 |     1500 |  1.2624193755 |  0.1403613304
    16 |     1600 |  0.9464821032 |  0.1403613304
    17 |     1700 |  0.6683186418 |  0.0979941744
    18 |     1800 |  0.5448472529 |  0.0979941744
    19 |     1900 |  0.4106950342 |  0.0688337904


In [5]:
res.pop

Population([<pymoo.core.individual.Individual object at 0x7ff3ec2679d0>,
           dtype=object)

In [6]:
[x.get("X") for x in res.pop]

[array([ 1.44058933e-09, -3.40926300e-06]),
 array([ 1.43964292e-09, -3.40926300e-06]),
 array([ 1.44031678e-09, -3.40926300e-06]),
 array([ 1.44020568e-09, -3.40926300e-06]),
 array([ 1.4395608e-09, -3.4092630e-06]),
 array([ 1.43959345e-09, -3.40926300e-06]),
 array([ 1.44248716e-09, -3.40926300e-06]),
 array([ 1.44019595e-09, -3.40926300e-06]),
 array([ 1.43942726e-09, -3.40926300e-06]),
 array([ 1.4399395e-09, -3.4092630e-06]),
 array([ 1.44038755e-09, -3.40926300e-06]),
 array([ 1.44019274e-09, -3.40926300e-06]),
 array([ 1.4403134e-09, -3.4092630e-06]),
 array([ 1.4395528e-09, -3.4092630e-06]),
 array([ 1.4403191e-09, -3.4092630e-06]),
 array([ 1.44260909e-09, -3.40926300e-06]),
 array([ 1.44031933e-09, -3.40926300e-06]),
 array([ 1.43993605e-09, -3.40926300e-06]),
 array([ 1.44092946e-09, -3.40926300e-06]),
 array([ 1.44019302e-09, -3.40926300e-06]),
 array([ 1.44032023e-09, -3.40926300e-06]),
 array([ 1.43993549e-09, -3.40926300e-06]),
 array([ 1.43964214e-09, -3.40926300e-06])

In [22]:
res.algorithm.callback.data["best"][0].shape

(100, 1)

In [8]:
def check_if_conv(k , eps ,  cb):
    f = [np.mean(cb.data["best"][i]) for i in range(len(cb.data["best"]))]

    for i in range(len(f) - k):
        if ((max(f[i:i + k]) - min(f[i:i+k])) < eps):
            return i+k
    return -1



In [9]:
check_if_conv(5  , 1e-5, res.algorithm.callback)

85

In [10]:
problem